name: Build Web App
 
on: [push]
 
jobs:
  DatabaseStructureBuild:
    runs-on: windows-latest 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'     
    - name: Restore NuGet Packages
      run: nuget restore ./DatabaseStructure/DatabaseStructure.csproj
    - name: Build Database Structure
      run: msbuild ./DatabaseStructure/DatabaseStructure.csproj
      
  ServiceLayerBuild:
    runs-on: windows-latest 
    needs:
      - DatabaseStructureBuild
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'     
    - name: Restore NuGet Packages
      run: nuget restore ./ServiceLayer/ServiceLayer.csproj
    - name: Build Library
      run: msbuild ./ServiceLayer/ServiceLayer.csproj
      
  Build: 
    runs-on: windows-latest 
    needs:
    - ServiceLayerBuild
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'     
    - name: Restore NuGet Packages
      run: nuget restore EducationalSystem.sln 
    - name: Build Web App
      run: msbuild EducationalSystem.sln     
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    - name: Run Unit Tests
      run: vstest.console.exe ./EducationalSystem.Test/bin/Debug/net5.0/EducationalSystem.Test.dll
