name: Build Web App
 
on: [push]
 
jobs:
  ServiceBuild:
    runs-on: windows-latest 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'     
    - name: Restore NuGet Packages
      run: nuget restore EducationalSystem.sln
    - name: Build Database Structure
      run: msbuild ./DatabaseStructure/DatabaseStructure.csproj
    - name: Build Service Layer
      run: msbuild ./ServiceLayer/ServiceLayer.csproj   
    - name: Build Web App
      run: msbuild EducationalSystem.sln     
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    - name: Run Unit Tests
      run: vstest.console.exe ./EducationalSystem.Test/bin/Debug/net5.0/EducationalSystem.Test.dll
   
  AngularBuild:
   runs-on: ubuntu-latest
   continue-on-error: false
   steps:
    - uses: actions/checkout@v1
      name: Checkout Code 
    - name: Setup Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Setup
      run: npm ci
    - name: Install NPM Modules
      working-directory: ./EducationalSystem.WebAPI/NgApp
      run: npm install
    - name: Build Angular App
      working-directory: ./EducationalSystem.WebAPI/NgApp
      run: npm run build
    - name: Install Browser for Test
      working-directory: ./EducationalSystem.WebAPI/NgApp
      run: npm i -D puppeteer karma-chrome-launcher
    - name: Test Angular App
      working-directory: ./EducationalSystem.WebAPI/NgApp
      run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  
  BDDTests:
   runs-on: windows-latest 
   needs:
    - ServiceBuild
    - AngularBuild
   steps:
    - uses: actions/checkout@v1
      name: Checkout Code     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'     
    - name: Restore NuGet Packages
      run: nuget restore ./EducationalSystem.BDDTesting/EducationalSystem.BDDTesting.sln
    - name: Build Tests App
      run: msbuild ./EducationalSystem.BDDTesting/EducationalSystem.BDDTesting.sln
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    - name: Run Gerkin Tests
      run: vstest.console.exe ./EducationalSystem.BDDTesting/EducationalSystem.BDDTesting.sln
